---
- Network:
    - AdGuard:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/adguard-home.svg'
        href: https://adguard.domain.ext
        target: _blank
        description: ""
        siteMonitor: https://adguard.domain.ext
        widget:
          type: adguard
          url: https://adguard.domain.ext
          username: {{HOMEPAGE_VAR_ADGUARD_USER}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Traefik:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/traefik.svg'
        href: http://traefik.domain.ext
        target: _blank
        description: ""
        server: my-docker
        container: traefik
        ping: traefik.domain.ext
        widget:
          type: traefik
          url: https://traefik.domain.ext
          username: {{HOMEPAGE_VAR_TRAEFIK_USER}}
          password: {{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}
    - Router:
        icon: ''
        href: https://router.domain.ext
        target: _blank
        description: ""
        ping: router.domain.ext
        siteMonitor: https://router.domain.ext

- Infrastructure and Data:
    - Proxmox:
        href: https://prx.domain.ext
        icon: proxmox.png
        description: ""
        siteMonitor: https://prx.domain.ext
        ping: prx.domain.ext
        widget:
          type: proxmox
          url: https://prx.domain.ext
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          fields: ['vms', 'resources.cpu', 'resources.mem']
    - Pgadmin4:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/pgadmin.svg'
        href: https://pgadmin.domain.ext
        description: ""
        server: my-docker
        container: pgadmin
        ping: pgadmin.domain.ext
    - RedisInsight:
        icon: 'https://cdn.icon-icons.com/icons2/2415/PNG/512/redis_plain_logo_icon_146366.png'
        href: https://redisinsight.domain.ext
        description: ""
        server: my-docker
        container: redisinsight
        ping: redisinsight.domain.ext
    - Gitea:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/gitea.svg'
        href: https://gitea.domain.ext
        description: ""
        server: my-docker
        container: gitea
        ping: gitea.domain.ext
        widget:
          type: gitea
          url: https://gitea.domain.ext
          key: {{HOMEPAGE_VAR_GITEA_TOKEN}}
    - Drone:
        icon: 'https://miro.medium.com/v2/resize:fit:256/0*AqO_2lNemh_Fl9Gm.png'
        href: https://drone.domain.ext
        description: ""
        server: my-docker
        container: drone
        ping: drone.domain.ext
    - Semaphore:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/semaphore.svg'
        href: https://semaphore.domain.ext
        description: ""
        ping: semaphore.domain.ext
    - Authentik:
        icon: 'https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/svg/authentik.svg'
        href: https://authentik.domain.ext
        description: ""
        server: my-docker
        container: authentik
        ping: authentik.domain.ext
        widget:
          type: authentik
          url: https://authentik.domain.ext
          key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}}
          version: 2
          fields:
            ["users", "loginsLast24H", "failedLoginsLast24H"]

- Resources:
    - NAS:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/synology.svg'
        href: https://nas.domain.ext
        target: _blank
        description: ""
        ping: nas.domain.ext
        siteMonitor: https://nas.domain.ext
    - Mattermost:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/mattermost.svg'
        href: https://mattermost.domain.ext
        description: ""
        server: my-docker
        container: mattermost
        ping: mattermost.domain.ext
    - Gotify:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/gotify.svg'
        href: https://gotify.domain.ext
        description: ""
        server: my-docker
        container: gotify
        ping: gotify.domain.ext
    - Jellyfin:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/jellyfin.svg'
        href: https://jellyfin.domain.ext
        description: ""
        ping: jellyfin.domain.ext
        widget:
          type: jellyfin
          url: https://jellyfin.domain.ext
          key: {{HOMEPAGE_VAR_JF_KEY}}
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false
    - Jellyseer:
        icon: 'https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/svg/jellyseerr.svg'
        href: https://jellyseer.domain.ext
        description: ""
        ping: jellyseer.domain.ext
        widget:
          type: jellyseerr
          url: https://jellyseer.domain.ext
          key: {{HOMEPAGE_VAR_JS_KEY}}
          fields: ["pending", "approved", "available"]
    - Outline:
        icon: 'https://www.getoutline.com/images/logo.svg'
        href: https://outline.domain.ext
        description: ""
        server: my-docker
        container: outline
        ping: outline.domain.ext
    - Mealie:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/mealie.svg'
        href: https://mealie.domain.ext
        description: ""
        server: my-docker
        container: mealie
        ping: mealie.domain.ext
        widget:
          type: mealie
          url: https://mealie.domain.ext
          key: {{HOMEPAGE_VAR_MEALIE_KEY}}
          fields: ['recipes', 'users', 'categories', 'tags']
          version: 2

- Bittorrent:
    - Qbittorrent:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/qbittorrent.svg'
        href: https://qt.domain.ext
        description: ""
        ping: qt.domain.ext
    - Prowlarr:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/prowlarr.svg'
        href: https://pw.domain.ext
        description: ""
        ping: pw.domain.ext

- Monitoring:
    - Uptime-Kuma:
        icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/1385e150f515795aa078bdbae2b8cdafb7567368/svg/uptime-kuma.svg'
        href: https://uptimekuma.domain.ext
        description: ""
        server: my-docker
        container: uptimekuma
        ping: uptimekuma.domain.ext
        widget:
          type: uptimekuma
          url: https://uptimekuma.domain.ext
          slug: homepage
    - Grafana:
        href: https://grafana.domain.ext
        description: ""
        icon: grafana.png
        server: my-docker
        container: grafana
        ping: grafana.domain.ext
        widget:
          type: grafana
          url: https://grafana.domain.ext
          username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
          fields: ['dashboards', 'datasources', 'totalalerts', 'alertstriggered']
    - Prometheus:
        href: https://prometheus.domain.ext
        description: ""
        icon: prometheus.png
        server: my-docker
        container: prometheus
        ping: prometheus.domain.ext
        widget:
          type: prometheus
          url: https://prometheus.domain.ext